# Generated by Django 5.0.6 on 2025-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='network/profile_pics/default.jpg', null=True, upload_to='network/profile_pics/'),
        ),
    ]
