# Generated by Django 5.0.6 on 2025-02-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='network/images/profile_pics/anonymous.jpg', null=True, upload_to='network/images/profile_pics/'),
        ),
    ]
