# Generated by Django 5.0.6 on 2025-02-15 22:37

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.user_profile_pic_path),
        ),
    ]
